### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by marado** [gato-chalupa/gato-chalupa.github.io#1]
Era interessante que este repositório tivesse uma licença de software livre ;-)

**Comment by lapisdecor** [comment]
Acrescenta-a. Ontem só tive tempo de fazer isto.

A sábado, 30/03/2024, 10:02, Marcos Marado ***@***.***>
escreveu:

**Comment by lapisdecor** [comment]
Que licença sugeres?

**Comment by lapisdecor** [comment]
Olha esquece, já não vou usar isto para fazer o projecto, ninguém contribui. Isto fica de reserva para outra coisa qualquer.
